module.exports.descriptors = [
    'Windy',
    'Lost',
    'Sunny',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Mount',
    'Redwood',
    'North',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Mission',
    'Sky',
    'Dusty',
    'Diamond', 
    'Angels',
    'Coyote', 
    'Meadows', 
    'Sierra', 
    'Eagle', 
    'Rancho', 
    'Morrow',
    'South', 
    'Mori',
    'Edgewood', 
    'Willow', 
    'Elysian', 
    'Griffith', 
    'Fern', 
    'Wonder View', 
    'Adams', 
    'Spring', 
    'Deer',
    'Edgewood', 
    'Keystone', 
    'Inglewood', 
    'Davidson', 
    'Mills', 
    'Wetlands', 
    'Saint James', 
    'Hunter', 
    'Grand',  
    'Enchanted',
    'Moore', 
    'Flathead', 
    'Gallagator', 
    'Rangers', 
    'Foothill',
    'Twin', 
    'Beacon', 
    'Tanglewood', 
    'Lexington', 
    'Labanon', 
    'Mileville', 
    'Thompson', 
    'Terrace', 
    'Hilltop', 
    'Whitetail'
]

module.exports.nouns = [
    'Rock',
    'Rocky', 
    'Gate', 
    'Ends',
    'Hill', 
    'Hills', 
    'Vista', 
    'Lane', 
    'Loop',
    'Loop', 
    'River',
    'Creek', 
    'Creek', 
    'Bike', 
    'Ridge', 
    'Creek', 
    'Bay', 
    'Shoreline', 
    'Mountain', 
    'Shore', 
    'Basin', 
    'Ranch', 
    'Lookout',
    'Falls', 
    'Ponds', 
    'Pass', 
    'Adobe', 
    'Nature', 
    'Pilchuck', 
    'Wallace',
    'Ghost Town', 
    'Point', 
    'Grove', 
    'West', 
    'Oak', 
    'Woods',
    'Bottoms', 
], 


// Repeated trail multiple times to increase the frequency of the word 
module.exports.places = [
    'Trail',
    'Trail',
    'Trail',
    'Trail',
    'Trail',
    'Trail',
    'Trail',
    'Trailhead', 
    'Trailhead', 

    'Park', 
    'Park',
    'Park',
    'County Park',
    'County Park',
    'County Park',
    'Regional Park',

    'Canyon',
    'Peak',
    'Summit',
    'Backcountry',
    'Preserve',
    'Cliffs',

    'Flats',
    'Bay',
    'Hollow',
]

